name: Testing on Ubuntu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo apt install -y perl cpanminus
        sudo cpanm --installdeps .
    - name: Install test dependencies
      run: |
        sudo cpanm Test::More File::Temp
    - name: Run unit tests
      run: |
        prove -lv tests/
    - name: Verify the basic usage
      run: |
        perl fuzzpm.pl